### ISSUE TITLE
Plugin does not work on windows. Use path.sep insted of "/".

### ISSUE THREAD

**Issue by Igorkowalski94** [eduhdm/eslint-plugin-repo-structure#6]
import path from "path";

Change all  "/" to path.sep in validatePath, filterRulesByType, validateRulesList

**Comment by eduhdm** [comment]
Hey @Igorkowalski94, sorry for the delay.

Added path normalization, it should work for windows now on version 0.1.1
Thanks for the feedback! 

If the issue persists, feel free to reopen an issue
